ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN nitijyokeizoku nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN kangotaisei_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN kangotaisei_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN nightdutyhaichi nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN semi_unitcare nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN private_kinou nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN jyakunenseinyusyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN doctor_haiti nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN seishinkairyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN syogaisyashien nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN taisyomaesoudan nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN taisyogosoudan nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN taisyojisoudan nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN taisyomaerenkei nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN eiyomanage nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN keikoikou nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN keikoiji nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN koukutaisei nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN kouku nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN medical_meal nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN caregiving nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN zaitakuhukki nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN zaitakunyusyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN nintisyosenmon_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN nintisyosenmon_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN nintisyoshinritaio nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN entrance_capacity nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN unit_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN unit_semi_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN existingroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN multibedroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN residence_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN special_room_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN special_meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN hairdressing_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN daily_life_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_welfare_facility] ALTER COLUMN userchargecut nvarchar(max) NULL
