ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN office_type_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN nightdutyhaichi nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN rehabilikyouka nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN private_rehabili nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN sub_nintisyocare nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN nintisyoshinritaio nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN kinkyutankiuke nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN jyakunenseiriyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN sub_jyudoryoyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN sougei_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN ryoyoiji_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN medical_meal nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN kinkyujitiryo nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN tokuteitiryo nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN unit_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN unit_semi_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN existingroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN multibedroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN stay_price_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN special_nursing_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN special_meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN hairdressing_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_health] ALTER COLUMN daily_life_price nvarchar(max) NULL
