ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN private_kinou nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN sub_night_nursing nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN medicalkikanrenkei nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN sub_caregiving nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN sub_shortuse_specified nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN personal_distribution nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN payment_method nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN lumpsum_name nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN lumpsum_num nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN lumpsum_from nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN lumpsum_to nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN lumpsum_avg nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN lumpsum_biko nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN repaymentrate nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN recoveryperiod nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN cancel_returnmoney nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN controlcost nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN controlcost_biko nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN mealprice nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN mealprice_biko nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN fuelprice nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN fuelprice_biko nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN personal_distributionyobo_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN personal_distributionyobo_2_biko nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN indivudual_selectyobo nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN indivudual_selectyobo_biko nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN eq_rent nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN eq_rent_from nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN eq_rent_to nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN eq_ent_avg nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN eq_rent_biko nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN other_getsugaku nvarchar(max) NULL
ALTER TABLE [dbo].[j_specified_lifecare_charge] ALTER COLUMN other_lumpsum nvarchar(max) NULL
