ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN office_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN service_area nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN kinkyujihoumon nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN specialkanri_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN specialkanri_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN terminalcare nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN taiinjikyoudousidou nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN tube_feeding nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN ivh nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN iv_drip nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN bladder_catheterization nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN nephrostomy nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN hot nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN respirator nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN capd nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN artificial_anus nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN artificial_bladder nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN tracheal_cannula nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN absorb nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN drug_pain_control nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN medical_other_name nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN medical_other nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN outarea_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN operator_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_routine_home] ALTER COLUMN userchargecut nvarchar(max) NULL
