ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN office_time_kayoi nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN office_time_stay nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN service_area nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN sougei_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN sub_nintisyo_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN sub_nintisyo_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN sub_kangohaiti_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN sub_kangohaiti_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN morning_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN lunch_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN dinner_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN snack_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN stay_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_name_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_price_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_biko_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_name_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_price_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_biko_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_name_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_price_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_biko_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_name_4 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_price_4 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_biko_4 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_name_5 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_price_5 nvarchar(max) NULL
ALTER TABLE [dbo].[v_small_multi_home] ALTER COLUMN other_biko_5 nvarchar(max) NULL
