ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN office_kubun nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN nightkango_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN nightkango_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN nightkango_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN nightkango_4 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN nothing_add nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN ryoyobyousyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN nintisyobyoto nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN jyakunenseikanjya nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN gaihaku nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN shikotekitaiinn nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN takajyushin nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN taiinmaeshido nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN taiingoshido nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN taiinjishido nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN taiinjiinfo nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN taiinmaerenkei nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN roujinkangoshiji nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN eiyomanage nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN keikoikou nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN keikoiji nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN koukutaisei nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN kouku nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN medical_meal nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN zaitakuhukki nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN tokuteishinryo nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN nintisyosenmon_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN nintisyosenmon_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN nintisyoshinritaio nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN entrance_capacity nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN unit_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN unit_semi_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN existingroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN multibedroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN residence_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN special_sickroom_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN special_meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN hairdressing_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_care_medical_facility] ALTER COLUMN daily_life_price nvarchar(max) NULL
