ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN night_care_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN night_care_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN nintisyoshinritaio nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN jyakunenseiriyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN sub_caregiving nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN sub_medicalrenkeitaisei nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN taikyojisoudan nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN nintisyosenmon_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN nintisyosenmon_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN shortuse_communal_lifecare nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN share_dementia_daycare nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN movein_capacity nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN rent nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN deposit nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN security_money nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN morning_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN lunch_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN dinner_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN snack_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN meal_day_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN hairdressing_price_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN hairdressing_biko_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN diaper_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN diaper_biko nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN other_name_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN other_price_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN other_biko_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN other_name_4 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN other_price_4 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN other_biko_4 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN other_name_5 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN other_price_5 nvarchar(max) NULL
ALTER TABLE [dbo].[j_dementia_communal_lifecare] ALTER COLUMN other_biko_5 nvarchar(max) NULL
