ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN nitijyokeizoku nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN kangotaisei_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN kangotaisei_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN nightdutyhaichi nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN semi_unitcare nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN private_kinou nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN jyakunenseinyusyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN doctor_haiti nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN seishinkairyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN syogaisyashien nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN taisyomaesoudan nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN taisyogoshido nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN taisyojisoudan nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN taisyomaerenkei nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN eiyomanage nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN keikoikou nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN keikoiji nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN koukutaisei nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN kouku nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN medical_meal nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN caregiving nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN zaitakuhukki nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN zaitakunyusyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN small_kyoten nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN nintisyosenmon_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN nintisyosenmon_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN nintisyoshinritaio nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN unit_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN unit_semi_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN existingroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN multibedroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN residence_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN special_room_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN special_meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN hairdressing_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN daily_life_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_local_based_welfare] ALTER COLUMN userchargecut nvarchar(max) NULL
