ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN office_kubun nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN nightkango_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN nightkango_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN nightkango_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN nightkango_4 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN nothing_add nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN ryoyobyousyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN nintisyobyoto nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN nintisyoshinritaio nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN sub_kinkyutankiuke nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN jyakunenseiriyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN sougei_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN medical_meal nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN unit_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN unit_semi_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN existingroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN multibedroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN stay_price_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN special_sickroom_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN special_meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN hairdressing_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_nursing_medical] ALTER COLUMN daily_life_price nvarchar(max) NULL
