ALTER TABLE [dbo].[j_short_life] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN office_type nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN sub_kinoukunrenshidoin nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN kinoukunrentaisei_yobo nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN sub_kangotaisei_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN sub_kangotaisei_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN sub_nightdutyhaichi nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN nintisyoshinritaio nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN jyakunenseiriyo nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN sougei_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN sub_kinkyutankitaisei nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN sub_kinkyutankiuke nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN medical_meal nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN sub_zaitakuuke nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN unit_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN unit_semi_privateroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN existingroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN multibedroom nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN stay_price_2 nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN special_room_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN special_meal_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN hairdressing_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN daily_life_price nvarchar(max) NULL
ALTER TABLE [dbo].[j_short_life] ALTER COLUMN userchargecut nvarchar(max) NULL
