ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN office_time_kayoi nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN office_time_stay nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN service_area nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN sougei_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN nintisyo_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN nintisyo_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN jigyokaishishien nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN kinkyujihoumon nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN specialkanri_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN specialkanri_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN terminalcare nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN service_supply_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN tube_feeding nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN ivh nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN iv_drip nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN bladder_catheterization nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN nephrostomy nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN hot nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN respirator nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN capd nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN artificial_anus nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN artificial_bladder nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN tracheal_cannula nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN absorb nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN drug_pain_control nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN medical_other_name nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN medical_other nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN morning_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN lunch_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN dinner_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN snack_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN stay_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_name_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_price_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_biko_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_name_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_price_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_biko_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_name_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_price_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_biko_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_name_4 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_price_4 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_biko_4 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_name_5 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_price_5 nvarchar(max) NULL
ALTER TABLE [dbo].[v_mix_service] ALTER COLUMN other_biko_5 nvarchar(max) NULL
