ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN office_time_week nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN office_time_sat nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN office_time_sun nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN office_time_hol nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN office_time_reghol nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN office_time_memo nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN service_time_week nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN service_time_sat nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN service_time_sun nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN service_time_hol nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN service_time_memo nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN service_area nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN operationcenter nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN route_service nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN zuijihoumon_service nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN hour_tuho nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN service_supply_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN service_supply_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN carestaffkaizen_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN carestaffkaizen_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN carestaffkaizen_3 nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN outarea_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN operator_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN cancel_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_night_home_care] ALTER COLUMN userchargecut nvarchar(max) NULL
