ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN office_time_week nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN office_time_sat nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN office_time_sun nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN office_time_hol nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN office_time_reghol nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN office_time_memo nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN service_area nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN chairtoilet nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN chairtoilet_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN chairtoilet_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN autoexcretionparts nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN autoexcretionparts_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN autoexcretionparts_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathchair nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathchair_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathchair_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathtubhandrail nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathtubhandrail_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathtubhandrail_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathtubchair nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathtubchair_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathtubchair_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathstand nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathstand_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathstand_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathroomsunoko nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathroomsunoko_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathroomsunoko_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathtubsunoko nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathtubsunoko_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathtubsunoko_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathassistbelt nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathassistbelt_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN bathassistbelt_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN simplebath nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN simplebath_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN simplebath_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN liftsling nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN liftsling_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN liftsling_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN outarea_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_specified_welfare_tool_sale] ALTER COLUMN welfaretoolcarry_price nvarchar(max) NULL
