ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN service_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN latitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN longitude nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN name nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN name_furi nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN company_type nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN company nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN postcode nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN municipality nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN address_1 nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN address_2 nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN tel nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN fax nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN hp_address nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN office_no nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN manager_name nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN founding_day nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN traffic nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN office_time_week nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN office_time_sat nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN office_time_sun nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN office_time_hol nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN office_time_reghol nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN office_time_memo nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN service_area nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN wheelchair nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN wheelchair_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN wheelchair_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN specialbed nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN specialbed_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN specialbed_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN bedsore nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN bedsore_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN bedsore_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN phyconverter nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN phyconverter_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN phyconverter_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN handrail nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN handrail_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN handrail_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN slope nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN slope_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN slope_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN walker nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN walker_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN walker_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN walkstick nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN walkstick_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN walkstick_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN dementialoiter nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN dementialoiter_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN dementialoiter_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN lift nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN lift_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN lift_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN autoexcretion nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN autoexcretion_price_from nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN autoexcretion_price_to nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN outarea_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN welfaretoolcarry_price nvarchar(max) NULL
ALTER TABLE [dbo].[v_welfare_tool_rental] ALTER COLUMN cancel_price nvarchar(max) NULL
