package util.common;

public class ColumnNames {
	public static final String OFFICE_ID = "office_id";
	public static final String SERCVICE_TYPE = "service_type";
	public static final String LATITUDE = "latitude";
	public static final String LONGITUDE = "longitude";
	public static final String NAME = "name";
	public static final String NAME_FURI = "name_furi";
	public static final String COMPANY_TYPE = "company_type";
	public static final String COMPANY = "company";
	public static final String POSTCODE = "postcode";
	public static final String ADDRESS_1 = "address_1";
	public static final String ADDRESS_2 = "address_2";
	public static final String TEL = "tel";
	public static final String FAX = "fax";
	public static final String HP_ADDRESS = "hp_address";
	public static final String OFFICE_NO = "office_no";
	public static final String MANAGER_NAME = "manager_name";
	public static final String FOUNDING_DAY = "founding_day";
	public static final String CANCEL_PRICE = "cancel_price";
	public static final String HAIRDRESSING_PRICE_2 = "hairdressing_price_2";
	public static final String STAY_PRICE = "stay_price";
	public static final String DIAPER_PRICE = "diaper_price";
	public static final String MEAL_DAY_PRICE = "meal_day_price";
	public static final String OPERATOR_PRICE = "operator_price";
	public static final String REPAYMENTRATE = "repaymentrate";
	public static final String RENT = "rent";
	public static final String DEPOSIT = "deposit";
	public static final String OTHER_BIKO_1 = "other_biko_1";
	public static final String OTHER_BIKO_2 = "other_biko_2";
	public static final String OTHER_BIKO_3 = "other_biko_3";
	public static final String OTHER_BIKO_4 = "other_biko_4";
	public static final String OTHER_BIKO_5 = "other_biko_5";
	public static final String HAIRDRESSING_BIKO_2 = "hairdressing_biko_2";
	public static final String DIAPER_BIKO = "diaper_biko";
	public static final String IVALIDATE_FLG = "ivaldate";
		
	public static final String TABLE_NAME = "table_name";
	public static final String SERVICE_NAME = "service_name";
	public static final String VALIDATE = "validate";
	public static final String VALIDATE_TYPE = "validate_type";
	public static final String COLUMN_NAME = "column_name";
	public static final String CONV_GROUP = "conv_group";
	public static final String CONV_LIST = "conv_list";
	public static final String VALID_GROUP = "valid_group";
	public static final String VALID_LIST = "valid_list";
	public static final String DATATYPE = "datatype";
	public static final String LENGTH = "length";
	public static final String J_FLG = "j_flg";
	public static final String FORMSERCD = "formSerCd";
	public static final String PRC_DATE = "prc_date";	
}
